### ISSUE TITLE
Cannot pass the settings of rust-analyer on Neovim over Neovim LSP

### ISSUE THREAD

**Issue by YuanYuYuan** [pr2502/ra-multiplex#15] opened 2023-02-07 08:05 UTC
Hi, @pr2502 , I really appreciate your work on ra-multiplex. It seems that neovim cannot pass the settings into the rust-analyzer while using ra-multiplex. Let me give you an example. You can run `luafile ./config.lua` in neovimn to check it.

_./config.lua_
```lua
require('lspconfig').rust_analyzer.setup {
    cmd = { "ra-multiplex" },
    settings = {
        ["rust-analyzer"] = {
            check = {
                overrideCommand = {
                    "cargo",
                    "clippy",
                    "--message-format=json-diagnostic-rendered-ansi",
                    "--fix",
                    "--allow-dirty"
                }
            }
        }
    }
}
```

If I comment out the line `cmd = { "ra-multiplex" }`, then neovim would run `cargo clippy`, which is exactly what I want. Do you have any thoughts about addressing this issue? Thanks.

**Comment by pr2502** [comment] 2023-02-07 08:12
Hi, can you please enable debug logging in ra-multiplex (`log_filters = "debug"` in `~/.config/ra-multiplex/config.toml`), try it again and attach the logged messages here, thanks!

**Comment by YuanYuYuan** [comment] 2023-02-07 08:25
Thanks for your rapid reply!

![image](https://user-images.githubusercontent.com/10692887/217191080-ec6ef632-455a-4f38-9373-ae34a509126f.png)

I'm afraid that nothing interesting was found.

**Comment by pr2502** [comment] 2023-02-07 09:44
I can't reproduce your neovim setup, you'll have to produce some logs yourself. I've found there is :LspLog command in the neovim lsp plugin, maybe you could log those while not using ra-multiplex and while using it to see the difference. My guess is either the command itself or the response to it comes as some notification without an ID and ra-multiplex can't forward those.

**Comment by YuanYuYuan** [comment] 2023-02-07 10:12
Yes, I had checked LspLog at the beginning, but nothing special was found. So I think I need to intercept the incoming setting JSON message from the client to the ra-multiplex wrapper. Or it might be the problem at neovim-lsp like it does not send the message at all.

**Comment by JeanMertz** [comment] 2023-04-21 11:43
I don't have anything useful to report (yet), but here's a "me too" comment, in that I have the exact same setup (NeoVim, `lspconfig`, and wanting to run `clippy` instead of `check`.

Unfortunately, ra-multiplex does not seem to honour the provided configuration currently. If/when I find some more time, I'll see if I can dig up some additional logs, but at first glance, nothing relevant is being logged currently.

**Comment by IndianBoy42** [comment] 2023-06-07 14:16
Remember to add `vim.lsp.set_log_level(vim.log.levels.DEBUG)` and `RUST_LOG=trace`  to basically see every rpc send and receive from both sides

https://pastebin.com/ALJ4TnBg

https://pastebin.com/xfB3qWyF

Could it be  the `response to no request` about a `workspace/configuration` message send from rust-analyzer, that doesn't go through to the neovim lsp client,  which thus doesn't respond with any configuration.

You can see neovim receiving it and then shortly after responding with the full settings table when I disable ra-multiplex

https://pastebin.com/Ajez5j4M

I believe this `response to no request` being dropped is expected behaviour? but then how do other clients work? configuration should also be sent through `didChangedConfiguration` so I don't think `workspace/configuration` being dropped should be a problem. 

currently you only `log::trace` messages received from the server, so I am not sure

**Comment by IndianBoy42** [comment] 2023-06-08 17:07
https://github.com/rust-lang/rust-analyzer/blob/9c03aa1ac2e67051db83a85baf3cfee902e4dd84/crates/rust-analyzer/src/handlers/notification.rs#L150

I'm not sure how (or if?) it worked with coc or any other client but ignoring `workspace/configuration` request from server to client will not work. 

`didChangeConfiguration` (although it contains all the config data for legacy sake) is not actually used to set the configuration. it is a notification to tell the server to ask the client for the configuration. 

This is spec compliant and what the maintainers of lsp want long term (https://github.com/microsoft/language-server-protocol/issues/972)

**Comment by jefftt** [comment] 2023-06-17 01:34
FWIW i got it to work by hardcoding the `initializationOptions` parameter in the proxied `InitializeRequest`. Not ideal but it gets the job done while we figure out a real solution. Can see the diff on my [branch](https://github.com/jefftt/ra-multiplex/commit/23b3f51c6fd38821c12f829c295071546018f51b)

**Comment by IndianBoy42** [comment] 2023-06-17 04:09
Oh I forgot to link it but I fixed it by handling workspace/configuration requests from the server

**Comment by jefftt** [comment] 2023-06-19 14:06
ah great! yes that's much better :)

**Comment by pr2502** [comment] 2023-10-25 01:56
We need to handle <https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#workspace_configuration> in some way.

#26 is an option but I think we should be more deliberate about how we handle each possible server request and fix this issue handling the `workspace/configuration` request only.

**Comment by pr2502** [comment] 2024-03-17 12:58
This should be fixed with <https://github.com/pr2502/ra-multiplex/pull/60>, I'll try to recreate a neovim setup and confirm myself but if someone can verify on their own setup it'd be very helpful^^

**Comment by YuanYuYuan** [comment] 2024-03-19 05:20
Hi @pr2502! Thanks for your update. The following configuration works for me. Saying, we can either change the check behavior or modify the feature flags now.
Hooray! :smile: 

```lua
require'lspconfig'.rust_analyzer.setup {
  cmd = vim.lsp.rpc.connect("127.0.0.1", 27631),
  init_options = {
    lspMux = {
      version = "1",
      method = "connect",
      server = "rust-analyzer",
    },
  },
  settings = {
    ["rust-analyzer"] = {
      check = {
        overrideCommand = {
            "cargo",
            "clippy",
            "--message-format=json-diagnostic-rendered-ansi",
            "--fix",
            "--allow-dirty"
        }
      },
      cargo = {
        features = "all",
      }
    }
  }
}
```

BTW, I notice that if I need to revert the modification or change the overrideCommand back to the default "cargo check", we need to specify the value explicitly to override the previous status of ra-multiplex (if we don't shutdown the server).

**Comment by WhyNotHugo** [comment] 2024-03-19 08:49
I can confirm that @YuanYuYuan's solution work on 189397dbc9b33b6a63fdc85f8a06a82a60ce1459.

**Comment by pr2502** [comment] 2024-03-19 10:52
Great! I'll close this now then^^

**Closed by pr2502** 2024-03-19 10:52 UTC
Labels: usability
